### ISSUE TITLE
icon problems

### ISSUE THREAD

**Issue by Zxurian** [maknz/slack#24]
so having some problems with the icon feature

setting it via the defaults, or with the `->withIcon()` method is not setting the icon on messages sent.

Using the v1.7.0 from packagist

**Comment by maknz** [comment]
Thanks, will look into it later today.

**Comment by maknz** [comment]
@Zxurian I can't reproduce this, everything is working totally as expected.

With an emoji, with `withIcon`:

```php
$c = new Maknz\Slack\Client('http://webhook.url')
$c->to('@regan')->withIcon(':ghost:')->send('hello from ghost');
```

With a URL:

```php
$c->to('@regan')->withIcon('https://slack.com/img/icons/app-57.png')->send('hello from slack');
```

and via defaults:

```php
$c = new Maknz\Slack\Client('http://webhook.url', ['icon' => ':heart_eyes:']);
$c->to('@regan')->send(':heart:');
```

A couple of things for you to try:

* If you're using a URL, make sure the URL is valid and accessible everywhere. If Slack can't load it, it won't display it.
* If you're using emoji, make sure the emoji is valid and is properly delimited by semicolons `:`. Try pasting what you're using as your icon into Slack to test.
* If there has been no other chat in Slack since the icon change, and the same bot speaks next, the icon won't change, as the messages will all stack under the same icon/username to save space, so no new icon is requested. If you break up the chat by typing something and try again, the bot should get the new icon.
