### ISSUE TITLE
Defer service provider registration

### ISSUE THREAD

**Issue by brunnoferreira** [maknz/slack#26]
@maknz,

Wouldn't deferring the registration by setting `$defer = true` be a better default for the project?
This seems to be the default behavior for most third-party providers and allows for better app performance.

As an example, we've been using your package on a big project, but only part of it should actually integrate with Slack (we're using it for debugging purposes). Most of our users won't even have the ability to trigger the Slack integration, but the service provider is being loaded nonetheless.

Thanks for your time and for a great package.

**Comment by maknz** [comment]
Makes sense. I'll implement and test that tonight.




Glad you like the package :-)

**Comment by maknz** [comment]
Right, so after a bit of research, since the service providers provide configuration, they [cannot be deferred](http://laravel.com/docs/master/providers#deferred-providers). I've had a look at a few Laravel packages that do both configuration and service container bindings, and none of them are deferred (e.g. [intervention/image](https://github.com/Intervention/image/blob/master/src/Intervention/Image/ImageServiceProviderLaravel5.php) and [graham-campbell/flysystem](https://github.com/GrahamCampbell/Laravel-Flysystem/blob/master/src/FlysystemServiceProvider.php). Could you point me in the direction of packages that overcome this issue (i.e. that defer bindings but also offer configuration?)

To theorise, the cost of instantiating a client to the service container shouldn't really have any effect. Unless Guzzle is reasonably heavy -- do you have any benchmarks?

**Comment by brunnoferreira** [comment]
I don't, actually. We have just started using your Slack package, and it integrates with a minor part of our system, so any benchmarks so far are nearly useless.

It was more of a philosophical input, rather than overcoming a known issue.
I was just looking for the best way to handle its usage, but failed to notice that there's some configuration being done apart from the bindings.

This definitely makes it inappropriate for deferring. So sorry for the mistake and for taking up some of your time. I'll go ahead and close this issue.

**Comment by maknz** [comment]
No worries, thanks for brining it up :-)

BTW, if efficiency is important, you can duplicate the service provider to your app namespace and defer it there, removing the config registration code and just have the service bindings. You might be susceptible to BC breaks, but it would be a workaround if needed.
